const Dogs = [
  {
    bred_for: "Small rodent hunting, lapdog",
    breed_group: "Toy",
    height: {
      imperial: "9 - 11.5",
      metric: "23 - 29",
    },
    id: 1,
    image: {
      height: 1199,
      id: "BJa4kxc4X",
      url: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
      width: 1600,
    },
    life_span: "10 - 12 years",
    name: "Affenpinscher",
    origin: "Germany, France",
    reference_image_id: "BJa4kxc4X",
    temperament: "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving",
    weight: {
      imperial: "6 - 13",
      metric: "3 - 6",
    },
  },
  {
    bred_for: "Coursing and hunting",
    breed_group: "Hound",
    country_code: "AG",
    height: {
      imperial: "25 - 27",
      metric: "64 - 69",
    },
    id: 2,
    image: {
      height: 380,
      id: "hMyT4CDXR",
      url: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
      width: 606,
    },
    life_span: "10 - 13 years",
    name: "Afghan Hound",
    origin: "Afghanistan, Iran, Pakistan",
    reference_image_id: "hMyT4CDXR",
    temperament: "Aloof, Clownish, Dignified, Independent, Happy",
    weight: {
      imperial: "50 - 60",
      metric: "23 - 27",
    },
  },
  {
    bred_for: "A wild pack animal",
    height: {
      imperial: "30",
      metric: "76",
    },
    id: 3,
    image: {
      height: 335,
      id: "rkiByec47",
      url: "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
      width: 500,
    },
    life_span: "11 years",
    name: "African Hunting Dog",
    origin: "",
    reference_image_id: "rkiByec47",
    temperament: "Wild, Hardworking, Dutiful",
    weight: {
      imperial: "44 - 66",
      metric: "20 - 30",
    },
  },
  {
    bred_for: "Badger, otter hunting",
    breed_group: "Terrier",
    height: {
      imperial: "21 - 23",
      metric: "53 - 58",
    },
    id: 4,
    image: {
      height: 430,
      id: "1-7cgoZSh",
      url: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
      width: 645,
    },
    life_span: "10 - 13 years",
    name: "Airedale Terrier",
    origin: "United Kingdom, England",
    reference_image_id: "1-7cgoZSh",
    temperament:
      "Outgoing, Friendly, Alert, Confident, Intelligent, Courageous",
    weight: {
      imperial: "40 - 65",
      metric: "18 - 29",
    },
  },
  {
    bred_for: "Sheep guarding",
    breed_group: "Working",
    height: {
      imperial: "28 - 34",
      metric: "71 - 86",
    },
    id: 5,
    image: {
      height: 471,
      id: "26pHT3Qk7",
      url: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
      width: 600,
    },
    life_span: "10 - 12 years",
    name: "Akbash Dog",
    origin: "",
    reference_image_id: "26pHT3Qk7",
    temperament: "Loyal, Independent, Intelligent, Brave",
    weight: {
      imperial: "90 - 120",
      metric: "41 - 54",
    },
  },

  {
    bred_for: "Guarding",
    breed_group: "Mixed",
    description:
      "The Alapaha Blue Blood Bulldog is a well-developed, exaggerated bulldog with a broad head and natural drop ears. The prominent muzzle is covered by loose upper lips. The prominent eyes are set well apart. The Alapaha's coat is relatively short and fairly stiff. Preferred colors are blue merle, brown merle, or red merle all trimmed in white or chocolate and white. Also preferred are the glass eyes (blue) or marble eyes (brown and blue mixed in a single eye). The ears and tail are never trimmed or docked. The body is sturdy and very muscular. The well-muscled hips are narrower than the chest. The straight back is as long as the dog is high at the shoulders. The dewclaws are never removed and the feet are cat-like.",
    height: {
      imperial: "18 - 24",
      metric: "46 - 61",
    },
    history: "",
    id: 7,
    image: {
      height: 2065,
      id: "33mJ-V3RX",
      url: "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
      width: 1828,
    },
    life_span: "12 - 13 years",
    name: "Alapaha Blue Blood Bulldog",
    reference_image_id: "33mJ-V3RX",
    temperament: "Loving, Protective, Trainable, Dutiful, Responsible",
    weight: {
      imperial: "55 - 90",
      metric: "25 - 41",
    },
  },
  {
    bred_for: "Sled pulling",
    breed_group: "Mixed",
    height: {
      imperial: "23 - 26",
      metric: "58 - 66",
    },
    id: 8,
    image: {
      height: 500,
      id: "-HgpNnGXl",
      url: "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
      width: 500,
    },
    life_span: "10 - 13 years",
    name: "Alaskan Husky",
    reference_image_id: "-HgpNnGXl",
    temperament: "Friendly, Energetic, Loyal, Gentle, Confident",
    weight: {
      imperial: "38 - 50",
      metric: "17 - 23",
    },
  },
  {
    bred_for: "Hauling heavy freight, Sled pulling",
    breed_group: "Working",
    height: {
      imperial: "23 - 25",
      metric: "58 - 64",
    },
    id: 9,
    image: {
      height: 769,
      id: "dW5UucTIW",
      url: "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
      width: 1023,
    },
    life_span: "12 - 15 years",
    name: "Alaskan Malamute",
    reference_image_id: "dW5UucTIW",
    temperament: "Friendly, Affectionate, Devoted, Loyal, Dignified, Playful",
    weight: {
      imperial: "65 - 100",
      metric: "29 - 45",
    },
  },
  {
    breed_group: "Working",
    height: {
      imperial: "22 - 27",
      metric: "56 - 69",
    },
    id: 10,
    image: {
      height: 1377,
      id: "pk1AAdloG",
      url: "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
      width: 1669,
    },
    life_span: "10 - 12 years",
    name: "American Bulldog",
    reference_image_id: "pk1AAdloG",
    temperament:
      "Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant",
    weight: {
      imperial: "60 - 120",
      metric: "27 - 54",
    },
  },
  {
    bred_for: "Family companion dog",
    breed_group: "",
    country_code: "US",
    height: {
      imperial: "14 - 17",
      metric: "36 - 43",
    },
    id: 11,
    image: {
      height: 683,
      id: "sqQJDtbpY",
      url: "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
      width: 1024,
    },
    life_span: "8 – 15 years",
    name: "American Bully",
    reference_image_id: "sqQJDtbpY",
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
    weight: {
      imperial: "30 - 150",
      metric: "14 - 68",
    },
  },
  {
    bred_for: "Circus performer",
    breed_group: "Non-Sporting",
    country_code: "US",
    height: {
      imperial: "15 - 19",
      metric: "38 - 48",
    },
    id: 12,
    image: {
      height: 802,
      id: "Bymjyec4m",
      url: "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
      width: 1000,
    },
    life_span: "12 - 15 years",
    name: "American Eskimo Dog",
    reference_image_id: "Bymjyec4m",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
    weight: {
      imperial: "20 - 40",
      metric: "9 - 18",
    },
  },
  {
    bred_for: "Companionship",
    country_code: "US",
    height: {
      imperial: "9 - 12",
      metric: "23 - 30",
    },
    id: 13,
    image: {
      height: 487,
      id: "_gn8GLrE6",
      url: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
      width: 730,
    },
    life_span: "13 – 15 years",
    name: "American Eskimo Dog (Miniature)",
    reference_image_id: "_gn8GLrE6",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
    weight: {
      imperial: "7 - 10",
      metric: "3 - 5",
    },
  },
  {
    bred_for: "Fox hunting, scent hound",
    breed_group: "Hound",
    country_code: "US",
    height: {
      imperial: "21 - 28",
      metric: "53 - 71",
    },
    id: 14,
    image: {
      height: 2400,
      id: "S14n1x9NQ",
      url: "https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg",
      width: 3000,
    },
    life_span: "8 - 15 years",
    name: "American Foxhound",
    reference_image_id: "S14n1x9NQ",
    temperament:
      "Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving",
    weight: {
      imperial: "65 - 75",
      metric: "29 - 34",
    },
  },
  {
    bred_for: "Fighting",
    breed_group: "Terrier",
    country_code: "US",
    height: {
      imperial: "17 - 21",
      metric: "43 - 53",
    },
    id: 15,
    image: {
      height: 244,
      id: "HkC31gcNm",
      url: "https://cdn2.thedogapi.com/images/HkC31gcNm.png",
      width: 300,
    },
    life_span: "10 - 15 years",
    name: "American Pit Bull Terrier",
    reference_image_id: "HkC31gcNm",
    temperament:
      "Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous",
    weight: {
      imperial: "30 - 60",
      metric: "14 - 27",
    },
  },
  {
    bred_for: "",
    breed_group: "Terrier",
    country_code: "US",
    height: {
      imperial: "17 - 19",
      metric: "43 - 48",
    },
    id: 16,
    image: {
      height: 500,
      id: "rJIakgc4m",
      url: "https://cdn2.thedogapi.com/images/rJIakgc4m.jpg",
      width: 357,
    },
    life_span: "12 - 15 years",
    name: "American Staffordshire Terrier",
    reference_image_id: "rJIakgc4m",
    temperament: "Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous",
    weight: {
      imperial: "50 - 60",
      metric: "23 - 27",
    },
  },
  {
    bred_for: "Bird flushing and retrieving",
    breed_group: "Sporting",
    country_code: "US",
    height: {
      imperial: "15 - 18",
      metric: "38 - 46",
    },
    id: 17,
    image: {
      height: 1264,
      id: "SkmRJl9VQ",
      url: "https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg",
      width: 1600,
    },
    life_span: "10 - 12 years",
    name: "American Water Spaniel",
    reference_image_id: "SkmRJl9VQ",
    temperament:
      "Friendly, Energetic, Obedient, Intelligent, Protective, Trainable",
    weight: {
      imperial: "25 - 45",
      metric: "11 - 20",
    },
  },
  {
    bred_for: "Livestock herding",
    breed_group: "Working",
    height: {
      imperial: "27 - 29",
      metric: "69 - 74",
    },
    id: 18,
    image: {
      height: 1131,
      id: "BJT0Jx5Nm",
      url: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg",
      width: 1216,
    },
    life_span: "11 - 13 years",
    name: "Anatolian Shepherd Dog",
    reference_image_id: "BJT0Jx5Nm",
    temperament: "Steady, Bold, Independent, Confident, Intelligent, Proud",
    weight: {
      imperial: "80 - 150",
      metric: "36 - 68",
    },
  },
  {
    bred_for: "Herding livestock, pulling carts, and guarding the farm",
    height: {
      imperial: "20 - 22",
      metric: "51 - 56",
    },
    id: 19,
    image: {
      height: 600,
      id: "HkNkxlqEX",
      url: "https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg",
      width: 400,
    },
    life_span: "12 – 14 years",
    name: "Appenzeller Sennenhund",
    reference_image_id: "HkNkxlqEX",
    temperament: "Reliable, Fearless, Energetic, Lively, Self-assured",
    weight: {
      imperial: "48 - 55",
      metric: "22 - 25",
    },
  },
  {
    bred_for: "Cattle herding, herding trials",
    breed_group: "Herding",
    country_code: "AU",
    height: {
      imperial: "17 - 20",
      metric: "43 - 51",
    },
    id: 21,
    image: {
      height: 850,
      id: "IBkYVm4v1",
      url: "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
      width: 736,
    },
    life_span: "12 - 14 years",
    name: "Australian Cattle Dog",
    reference_image_id: "IBkYVm4v1",
    temperament: "Cautious, Energetic, Loyal, Obedient, Protective, Brave",
    weight: {
      imperial: "44 - 62",
      metric: "20 - 28",
    },
  },
  {
    bred_for: "Farm dog, Cattle herding",
    breed_group: "Herding",
    country_code: "AU",
    height: {
      imperial: "17 - 20",
      metric: "43 - 51",
    },
    id: 22,
    image: {
      height: 533,
      id: "Hyq1ge9VQ",
      url: "https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg",
      width: 800,
    },
    life_span: "10 - 13 years",
    name: "Australian Kelpie",
    reference_image_id: "Hyq1ge9VQ",
    temperament: "Friendly, Energetic, Alert, Loyal, Intelligent, Eager",
    weight: {
      imperial: "31 - 46",
      metric: "14 - 21",
    },
  },
  {
    bred_for: "Sheep herding",
    breed_group: "Herding",
    country_code: "AU",
    height: {
      imperial: "18 - 23",
      metric: "46 - 58",
    },
    id: 23,
    image: {
      height: 733,
      id: "B1-llgq4m",
      url: "https://cdn2.thedogapi.com/images/B1-llgq4m.jpg",
      width: 1200,
    },
    life_span: "12 - 16 years",
    name: "Australian Shepherd",
    reference_image_id: "B1-llgq4m",
    temperament: "Good-natured, Affectionate, Intelligent, Active, Protective",
    weight: {
      imperial: "35 - 65",
      metric: "16 - 29",
    },
  },
 
];
export default Dogs;
